### ISSUE TITLE
Singular Header

### ISSUE THREAD

**Issue by lojikil** [cakinney/blockade#3]
https://github.com/TypeError/blockade/blob/1ba5907921fc35405bae71ee3446444ce3687382/src/headers.ts#L3

it seems like this class actually only abstracts a single header, so it should be  `HTTPHeader`, whereas `HTTPHeaders` may be a collective grouping thereof.

**Comment by cak** [comment]
Thanks @lojikil, great catch! I renamed the `HTTPHeaders` class to `HTTPHeader` and removed the unused export.
